name: update Readme

on:
    schedule:
        # Runs at 00:00AM UTC
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    update-waka-stats:
        name: Update this repo's README
        runs-on: ubuntu-latest
        steps:
            - uses: anmol098/waka-readme-stats@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  SHOW_OS: 'True'
                  SHOW_EDITORS: 'True'
                  SHOW_LANGUAGE: 'True'
                  SHOW_LANGUAGE_PER_REPO: 'True'
                  SHOW_PROJECTS: 'False'
                  LOCALE: 'en'
                  SHOW_TIMEZONE: 'False'
                  SHOW_SHORT_INFO: 'True'
                  SHOW_PROFILE_VIEWS: 'False'
                  SHOW_TOTAL_CODE_TIME: 'False'
                  SYMBOL_VERSION: 2
                  SHOW_UPDATED_DATE: 'False'
                  UPDATED_DATE_FORMAT: '%b %d, %Y'
                  SHOW_LOC_CHART: 'False' #see issue 337
                  SHOW_COMMIT: 'False'
                  SHOW_DAYS_OF_WEEK: 'False'
